// <auto-generated />
using System;
using BusinessReportingMVC.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BusinessReportingMVC.Migrations
{
    [DbContext(typeof(BusinessReportingDbContext))]
    [Migration("20250225130133_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BusinessReportingMVC.Models.AdminAndResource", b =>
                {
                    b.Property<long>("AdminAndResourcesId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("Admin_And_Resources_Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("AdminAndResourcesId"));

                    b.Property<string>("PointsOfNote")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Points_Of_Note");

                    b.HasKey("AdminAndResourcesId")
                        .HasName("PK__Admin_An__68A45A1D9A056FDD");

                    b.ToTable("Admin_And_Resources", (string)null);
                });

            modelBuilder.Entity("BusinessReportingMVC.Models.BusinessDevelopment", b =>
                {
                    b.Property<long>("BusinessDevelopmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("Business_Development_Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("BusinessDevelopmentId"));

                    b.Property<long>("BusinessDevelopmentNotesId")
                        .HasColumnType("bigint")
                        .HasColumnName("Business_Development_Notes_Id");

                    b.Property<long>("BusinessDevelopmentValueId")
                        .HasColumnType("bigint")
                        .HasColumnName("Business_Development_Value_Id");

                    b.HasKey("BusinessDevelopmentId")
                        .HasName("PK__Business__6B072B835A8DBE11");

                    b.HasIndex("BusinessDevelopmentNotesId");

                    b.HasIndex("BusinessDevelopmentValueId");

                    b.ToTable("Business_Development", (string)null);
                });

            modelBuilder.Entity("BusinessReportingMVC.Models.BusinessDevelopmentNote", b =>
                {
                    b.Property<long>("BusinessDevelopmentNotesId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("Business_Development_Notes_Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("BusinessDevelopmentNotesId"));

                    b.Property<string>("AwarenessNotes")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Awareness_Notes");

                    b.Property<string>("IntentNotes")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Intent_Notes");

                    b.Property<string>("Tendered033Notes")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Tendered_0_33_Notes");

                    b.Property<string>("Tendered3466Notes")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Tendered_34_66_Notes");

                    b.Property<string>("Tendered67100Notes")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Tendered_67_100_Notes");

                    b.HasKey("BusinessDevelopmentNotesId")
                        .HasName("PK__Business__183BA5824BDF1F67");

                    b.ToTable("Business_Development_Notes", (string)null);
                });

            modelBuilder.Entity("BusinessReportingMVC.Models.BusinessDevelopmentValue", b =>
                {
                    b.Property<long>("BusinessDevelopmentValueId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("Business_Development_Value_Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("BusinessDevelopmentValueId"));

                    b.Property<decimal?>("AwarenessValue")
                        .HasColumnType("money")
                        .HasColumnName("Awareness_Value");

                    b.Property<decimal?>("IntentValue")
                        .HasColumnType("money")
                        .HasColumnName("Intent_Value");

                    b.Property<decimal?>("Tendered033Value")
                        .HasColumnType("money")
                        .HasColumnName("Tendered_0_33_Value");

                    b.Property<decimal?>("Tendered3466Value")
                        .HasColumnType("money")
                        .HasColumnName("Tendered_34_66_Value");

                    b.Property<decimal?>("Tendered67100Value")
                        .HasColumnType("money")
                        .HasColumnName("Tendered_67_100_Value");

                    b.HasKey("BusinessDevelopmentValueId")
                        .HasName("PK__Business__3F0FE71E88EB7B09");

                    b.ToTable("Business_Development_Value", (string)null);
                });

            modelBuilder.Entity("BusinessReportingMVC.Models.Claim", b =>
                {
                    b.Property<long>("ClaimId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("Claim_Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ClaimId"));

                    b.Property<string>("ClaimName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Claim_Name");

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Claim_Type");

                    b.HasKey("ClaimId")
                        .HasName("PK__Claims__811C4A6D4D13DDD4");

                    b.ToTable("Claims");
                });

            modelBuilder.Entity("BusinessReportingMVC.Models.Financial", b =>
                {
                    b.Property<long>("FinancialsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("Financials_Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("FinancialsId"));

                    b.Property<long>("FinancialsActualId")
                        .HasColumnType("bigint")
                        .HasColumnName("Financials_Actual_Id");

                    b.Property<long>("FinancialsDeviationId")
                        .HasColumnType("bigint")
                        .HasColumnName("Financials_Deviation_Id");

                    b.HasKey("FinancialsId")
                        .HasName("PK__Financia__08CC3C0CA9ED1B46");

                    b.HasIndex("FinancialsActualId");

                    b.HasIndex("FinancialsDeviationId");

                    b.ToTable("Financials");
                });

            modelBuilder.Entity("BusinessReportingMVC.Models.FinancialsActual", b =>
                {
                    b.Property<long>("FinancialsActualId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("Financials_Actual_Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("FinancialsActualId"));

                    b.Property<decimal?>("CashPositionActual")
                        .HasColumnType("money")
                        .HasColumnName("Cash_Position_Actual");

                    b.Property<decimal?>("DirectCostsActual")
                        .HasColumnType("money")
                        .HasColumnName("Direct_Costs_Actual");

                    b.Property<decimal?>("GrossProfitActual")
                        .HasColumnType("money")
                        .HasColumnName("Gross_Profit_Actual");

                    b.Property<decimal?>("IndirectCostsActual")
                        .HasColumnType("money")
                        .HasColumnName("Indirect_Costs_Actual");

                    b.Property<decimal?>("NetProfitActual")
                        .HasColumnType("money")
                        .HasColumnName("Net_Profit_Actual");

                    b.Property<int?>("ProductionHoursQuarter")
                        .HasColumnType("int")
                        .HasColumnName("Production_Hours_Quarter");

                    b.Property<decimal?>("TurnoverActual")
                        .HasColumnType("money")
                        .HasColumnName("Turnover_Actual");

                    b.Property<decimal?>("UtilisationQuarter")
                        .HasColumnType("money")
                        .HasColumnName("Utilisation_Quarter");

                    b.Property<decimal?>("WipActual")
                        .HasColumnType("money")
                        .HasColumnName("WIP_Actual");

                    b.Property<int?>("WorkInHandHoursQuarter")
                        .HasColumnType("int")
                        .HasColumnName("Work_In_Hand_Hours_Quarter");

                    b.Property<decimal?>("WorkInHandMoneyQuarter")
                        .HasColumnType("money")
                        .HasColumnName("Work_In_Hand_Money_Quarter");

                    b.HasKey("FinancialsActualId")
                        .HasName("PK__Financia__E203C6A1AB11E293");

                    b.ToTable("Financials_Actual", (string)null);
                });

            modelBuilder.Entity("BusinessReportingMVC.Models.FinancialsDeviation", b =>
                {
                    b.Property<long>("FinancialsDeviationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("Financials_Deviation_Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("FinancialsDeviationId"));

                    b.Property<decimal?>("CashPositionForecast")
                        .HasColumnType("money")
                        .HasColumnName("Cash_Position_Forecast");

                    b.Property<decimal?>("DirectCostsDeviation")
                        .HasColumnType("money")
                        .HasColumnName("Direct_Costs_Deviation");

                    b.Property<decimal?>("GrossProfitDeviation")
                        .HasColumnType("money")
                        .HasColumnName("Gross_Profit_Deviation");

                    b.Property<decimal?>("IndirectCostsDeviation")
                        .HasColumnType("money")
                        .HasColumnName("Indirect_Costs_Deviation");

                    b.Property<decimal?>("NetProfitDeviation")
                        .HasColumnType("money")
                        .HasColumnName("Net_Profit_Deviation");

                    b.Property<int?>("ProductionHoursDeviation")
                        .HasColumnType("int")
                        .HasColumnName("Production_Hours_Deviation");

                    b.Property<decimal?>("TurnoverDeviation")
                        .HasColumnType("money")
                        .HasColumnName("Turnover_Deviation");

                    b.Property<decimal?>("UtilisationQuarter")
                        .HasColumnType("money")
                        .HasColumnName("Utilisation_Quarter");

                    b.Property<decimal?>("WipDeviation")
                        .HasColumnType("money")
                        .HasColumnName("WIP_Deviation");

                    b.Property<int?>("WorkInHandHoursQuarter")
                        .HasColumnType("int")
                        .HasColumnName("Work_In_Hand_Hours_Quarter");

                    b.Property<decimal?>("WorkInHandMoneyQuarter")
                        .HasColumnType("money")
                        .HasColumnName("Work_In_Hand_Money_Quarter");

                    b.HasKey("FinancialsDeviationId")
                        .HasName("PK__Financia__54D108BB5795E2D6");

                    b.ToTable("Financials_Deviation", (string)null);
                });

            modelBuilder.Entity("BusinessReportingMVC.Models.KeyHighlight", b =>
                {
                    b.Property<long>("KeyHighlightsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("Key_Highlights_Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("KeyHighlightsId"));

                    b.Property<string>("Opportunities")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Performance")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Risks")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("KeyHighlightsId")
                        .HasName("PK__Key_High__257931E987896825");

                    b.ToTable("Key_Highlights", (string)null);
                });

            modelBuilder.Entity("BusinessReportingMVC.Models.Project", b =>
                {
                    b.Property<long>("ProjectId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("Project_Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ProjectId"));

                    b.Property<decimal?>("ForecastOverallDeviation")
                        .HasColumnType("money")
                        .HasColumnName("Forecast_Overall_Deviation");

                    b.Property<decimal?>("ForecastOverallForecast")
                        .HasColumnType("money")
                        .HasColumnName("Forecast_Overall_Forecast");

                    b.HasKey("ProjectId")
                        .HasName("PK__Projects__1CB92E037A0932F6");

                    b.ToTable("Projects");
                });

            modelBuilder.Entity("BusinessReportingMVC.Models.ProjectIndividual", b =>
                {
                    b.Property<long>("ProjectIndividualId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("Project_Individual_Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ProjectIndividualId"));

                    b.Property<decimal?>("Deviation")
                        .HasColumnType("money");

                    b.Property<decimal?>("ForecastProfit")
                        .HasColumnType("money")
                        .HasColumnName("Forecast_Profit");

                    b.Property<bool?>("IsBottom")
                        .HasColumnType("bit")
                        .HasColumnName("Is_Bottom");

                    b.Property<byte?>("Position")
                        .HasColumnType("tinyint");

                    b.Property<int?>("ProjectCode")
                        .HasColumnType("int")
                        .HasColumnName("Project_Code");

                    b.Property<long>("ProjectId")
                        .HasColumnType("bigint")
                        .HasColumnName("Project_Id");

                    b.Property<string>("ProjectName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Project_Name");

                    b.HasKey("ProjectIndividualId")
                        .HasName("PK__Project___D45D6EACB196AC01");

                    b.HasIndex("ProjectId");

                    b.ToTable("Project_Individual", (string)null);
                });

            modelBuilder.Entity("BusinessReportingMVC.Models.Report", b =>
                {
                    b.Property<long>("ReportId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("Report_Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ReportId"));

                    b.Property<long>("AdminAndResourcesId")
                        .HasColumnType("bigint")
                        .HasColumnName("Admin_And_Resources_Id");

                    b.Property<long>("BusinessDevelopmentId")
                        .HasColumnType("bigint")
                        .HasColumnName("Business_Development_Id");

                    b.Property<long>("CreatedByUserId")
                        .HasColumnType("bigint")
                        .HasColumnName("Created_By_User_Id");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime")
                        .HasColumnName("Created_Date");

                    b.Property<long>("FinancialsId")
                        .HasColumnType("bigint")
                        .HasColumnName("Financials_Id");

                    b.Property<DateTime?>("FromDateRange")
                        .HasColumnType("datetime")
                        .HasColumnName("From_Date_Range");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasColumnName("Is_Deleted");

                    b.Property<bool>("IsDraft")
                        .HasColumnType("bit")
                        .HasColumnName("Is_Draft");

                    b.Property<long>("KeyHighlightsId")
                        .HasColumnType("bigint")
                        .HasColumnName("Key_Highlights_Id");

                    b.Property<long>("ProjectId")
                        .HasColumnType("bigint")
                        .HasColumnName("Project_Id");

                    b.Property<string>("ReportName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Report_Name");

                    b.Property<long>("StrategyId")
                        .HasColumnType("bigint")
                        .HasColumnName("Strategy_Id");

                    b.Property<DateTime?>("ToDateRange")
                        .HasColumnType("datetime")
                        .HasColumnName("To_Date_Range");

                    b.HasKey("ReportId")
                        .HasName("PK__Reports__30FA9DD1D8F4FD4E");

                    b.HasIndex("AdminAndResourcesId");

                    b.HasIndex("BusinessDevelopmentId");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("FinancialsId");

                    b.HasIndex("KeyHighlightsId");

                    b.HasIndex("ProjectId");

                    b.HasIndex("StrategyId");

                    b.ToTable("Reports");
                });

            modelBuilder.Entity("BusinessReportingMVC.Models.Strategy", b =>
                {
                    b.Property<long>("StrategyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("Strategy_Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("StrategyId"));

                    b.Property<string>("BusinessDevelopment")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Business_Development");

                    b.Property<string>("Innovation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Other")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("StrategyId")
                        .HasName("PK__Strategy__E5DD67A37457D499");

                    b.ToTable("Strategy", (string)null);
                });

            modelBuilder.Entity("BusinessReportingMVC.Models.User", b =>
                {
                    b.Property<long>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("User_Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("UserId"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsApproved")
                        .HasColumnType("bit")
                        .HasColumnName("Is_Approved");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Salt")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId")
                        .HasName("PK__Users__206D9170FEAFF174");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("BusinessReportingMVC.Models.UserClaim", b =>
                {
                    b.Property<long>("UserClaimsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("User_Claims_Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("UserClaimsId"));

                    b.Property<long>("ClaimId")
                        .HasColumnType("bigint")
                        .HasColumnName("Claim_Id");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("User_Id");

                    b.HasKey("UserClaimsId")
                        .HasName("PK__User_Cla__F98D208FD8673F6A");

                    b.HasIndex("ClaimId");

                    b.HasIndex("UserId");

                    b.ToTable("User_Claims", (string)null);
                });

            modelBuilder.Entity("BusinessReportingMVC.Models.BusinessDevelopment", b =>
                {
                    b.HasOne("BusinessReportingMVC.Models.BusinessDevelopmentNote", "BusinessDevelopmentNotes")
                        .WithMany("BusinessDevelopments")
                        .HasForeignKey("BusinessDevelopmentNotesId")
                        .IsRequired()
                        .HasConstraintName("FK_Business_Development_Notes_Id");

                    b.HasOne("BusinessReportingMVC.Models.BusinessDevelopmentValue", "BusinessDevelopmentValue")
                        .WithMany("BusinessDevelopments")
                        .HasForeignKey("BusinessDevelopmentValueId")
                        .IsRequired()
                        .HasConstraintName("FK_Business_Development_Value_Id");

                    b.Navigation("BusinessDevelopmentNotes");

                    b.Navigation("BusinessDevelopmentValue");
                });

            modelBuilder.Entity("BusinessReportingMVC.Models.Financial", b =>
                {
                    b.HasOne("BusinessReportingMVC.Models.FinancialsActual", "FinancialsActual")
                        .WithMany("Financials")
                        .HasForeignKey("FinancialsActualId")
                        .IsRequired()
                        .HasConstraintName("FK_Financials_Actual_Id");

                    b.HasOne("BusinessReportingMVC.Models.FinancialsDeviation", "FinancialsDeviation")
                        .WithMany("Financials")
                        .HasForeignKey("FinancialsDeviationId")
                        .IsRequired()
                        .HasConstraintName("FK_Financials_Deviation_Id");

                    b.Navigation("FinancialsActual");

                    b.Navigation("FinancialsDeviation");
                });

            modelBuilder.Entity("BusinessReportingMVC.Models.ProjectIndividual", b =>
                {
                    b.HasOne("BusinessReportingMVC.Models.Project", "Project")
                        .WithMany("ProjectIndividuals")
                        .HasForeignKey("ProjectId")
                        .IsRequired()
                        .HasConstraintName("FK_Project_Individual_Project_Id");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("BusinessReportingMVC.Models.Report", b =>
                {
                    b.HasOne("BusinessReportingMVC.Models.AdminAndResource", "AdminAndResources")
                        .WithMany("Reports")
                        .HasForeignKey("AdminAndResourcesId")
                        .IsRequired()
                        .HasConstraintName("FK_Admin_And_Resources");

                    b.HasOne("BusinessReportingMVC.Models.BusinessDevelopment", "BusinessDevelopment")
                        .WithMany("Reports")
                        .HasForeignKey("BusinessDevelopmentId")
                        .IsRequired()
                        .HasConstraintName("FK_Business_Development_Id");

                    b.HasOne("BusinessReportingMVC.Models.User", "CreatedByUser")
                        .WithMany("Reports")
                        .HasForeignKey("CreatedByUserId")
                        .IsRequired()
                        .HasConstraintName("FK_Created_By_User_Id");

                    b.HasOne("BusinessReportingMVC.Models.Financial", "Financials")
                        .WithMany("Reports")
                        .HasForeignKey("FinancialsId")
                        .IsRequired()
                        .HasConstraintName("FK_Financials_Id");

                    b.HasOne("BusinessReportingMVC.Models.KeyHighlight", "KeyHighlights")
                        .WithMany("Reports")
                        .HasForeignKey("KeyHighlightsId")
                        .IsRequired()
                        .HasConstraintName("FK_Key_Highlights_Id");

                    b.HasOne("BusinessReportingMVC.Models.Project", "Project")
                        .WithMany("Reports")
                        .HasForeignKey("ProjectId")
                        .IsRequired()
                        .HasConstraintName("FK_Project_Id");

                    b.HasOne("BusinessReportingMVC.Models.Strategy", "Strategy")
                        .WithMany("Reports")
                        .HasForeignKey("StrategyId")
                        .IsRequired()
                        .HasConstraintName("FK_Strategy_Id");

                    b.Navigation("AdminAndResources");

                    b.Navigation("BusinessDevelopment");

                    b.Navigation("CreatedByUser");

                    b.Navigation("Financials");

                    b.Navigation("KeyHighlights");

                    b.Navigation("Project");

                    b.Navigation("Strategy");
                });

            modelBuilder.Entity("BusinessReportingMVC.Models.UserClaim", b =>
                {
                    b.HasOne("BusinessReportingMVC.Models.Claim", "Claim")
                        .WithMany("UserClaims")
                        .HasForeignKey("ClaimId")
                        .IsRequired()
                        .HasConstraintName("FK_Claims_Id");

                    b.HasOne("BusinessReportingMVC.Models.User", "User")
                        .WithMany("UserClaims")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK_User_Claims");

                    b.Navigation("Claim");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BusinessReportingMVC.Models.AdminAndResource", b =>
                {
                    b.Navigation("Reports");
                });

            modelBuilder.Entity("BusinessReportingMVC.Models.BusinessDevelopment", b =>
                {
                    b.Navigation("Reports");
                });

            modelBuilder.Entity("BusinessReportingMVC.Models.BusinessDevelopmentNote", b =>
                {
                    b.Navigation("BusinessDevelopments");
                });

            modelBuilder.Entity("BusinessReportingMVC.Models.BusinessDevelopmentValue", b =>
                {
                    b.Navigation("BusinessDevelopments");
                });

            modelBuilder.Entity("BusinessReportingMVC.Models.Claim", b =>
                {
                    b.Navigation("UserClaims");
                });

            modelBuilder.Entity("BusinessReportingMVC.Models.Financial", b =>
                {
                    b.Navigation("Reports");
                });

            modelBuilder.Entity("BusinessReportingMVC.Models.FinancialsActual", b =>
                {
                    b.Navigation("Financials");
                });

            modelBuilder.Entity("BusinessReportingMVC.Models.FinancialsDeviation", b =>
                {
                    b.Navigation("Financials");
                });

            modelBuilder.Entity("BusinessReportingMVC.Models.KeyHighlight", b =>
                {
                    b.Navigation("Reports");
                });

            modelBuilder.Entity("BusinessReportingMVC.Models.Project", b =>
                {
                    b.Navigation("ProjectIndividuals");

                    b.Navigation("Reports");
                });

            modelBuilder.Entity("BusinessReportingMVC.Models.Strategy", b =>
                {
                    b.Navigation("Reports");
                });

            modelBuilder.Entity("BusinessReportingMVC.Models.User", b =>
                {
                    b.Navigation("Reports");

                    b.Navigation("UserClaims");
                });
#pragma warning restore 612, 618
        }
    }
}
